### ISSUE TITLE
Version de los RData

### ISSUE THREAD

**Issue by hermesh2** [rubenfcasal/COVID-19#1]
Hola Rubén,

te escribi un email. Estas utilizando una versión si quieres mantener las dos te mando este enlace también por acá

https://stackoverflow.com/questions/12463583/the-cause-of-bad-magic-number-error-when-loading-a-workspace-and-how-to-avoid

Abrazo

**Comment by hermesh2** [comment]
Solución
https://stackoverflow.com/questions/46875289/r-download-rdata 
 
rm(list = ls())
con<-url('https://github.com/rubenfcasal/COVID-19/blob/master/acumula22.RData?raw=true') # Create connexion
load(con) #Load the data
close(con) #close connexion


url <- "https://github.com/rubenfcasal/COVID-19/blob/master/acumula22.RData?raw=true"

download.file(url, destfile= "dat22.RData", mode = "ab")
download.file(url, destfile= "dat22.RData", mode = "wb")
load("dat22.RData")

**Comment by rubenfcasal** [comment]
Como apunta en la solución el problema es el modo de conexión por defecto en windows al descargar archivos con download.file().
